console.log("home.js loaded");
const container = document.getElementsByClassName("container");
console.log(container);
container[0].innerHTML = "<h3><b>Wodapalooza</b></h3><p>There aren’t many functional fitness events as impressive as Wodapalooza – which isn’t surprising when you consider that not only is it one of the CrossFit sanctioned events, but it also takes place in the enormous open venue at Miami’s Bayfront Park. The four-day festival is heavily focused on inclusivity, with divisions including teen, adaptive, scaled, masters, intermediate and Rx'd athletes. There’s also a one-day Olympic lifting competition as well as seminars, workshops and the chance to visit over 100 exhibitors over the duration of the festival. Last year saw 1,590 athletes take part in the event itself, although those places have to be earned via the online qualification process or through application to the scaled competition – that’s unless you’re a top athlete and you get invited along to take part. Online qualifiers for individuals takes place from 3 October, or 12 November if you’re hoping to get in as part of a team.</p>";
container[1].innerHTML = "<h3><b> The Battle of Riga </b></h3><p>The 2018 Battle of Riga not only saw some of the most gruelling functional challengesyou’re ever likely to find, but they also threw in a section where you hammer out 100 calories on an assault bike before jumping into a pool for a max length swim. As functional workouts go, it doesn’t get more varied than that. Qualifiers take place over two weeks in April and May, with athlete classes coveringelites, sport, over 35s (men) and over 40s (men) – the elites battling it out for a€6,500 prize pot across the three best athletes in each gender group. Fancy trying out the workouts from the 2018 event? Then you can find each of the sixWODs, including the swim, on the event website.</p>";
container[2].innerHTML = "<h3><b>Hyrox Berlin</b></h3><p>Hyrox is by far one of the most impressive fitness competitions we’ve seen and the fastest-growing in terms of locations and competitors. Individual tournaments take placein cities across Europe throughout the year and include the sort of technical set-upyou'd expect to see at the CrossFit Games. Previous formats have seen participants running for 1km before completing a functional workout, repeating the format eight times with a different functional section until finally crossing the finish line.So, unlike some of the other competitions out there, the idea is that you’re in with a chance whether you’re a CrossFitter, a cyclist, a runner or anything else that might make you fit.</p > ";

var content = '<div class="card"><img src="images/original.20210303-061419.jpg" alt="image"><div class="container"><h3><b>SITC Virtual - KpopX Fitness (True Fitness @ Djitsun Mall AMK)</b></h3><p>The SITC programme is brought to you by the Health Promotion Board (HPB). KpopX Fitness: A cardio dance workout that combines KPOP music and its signature moves with aerobic exercises to increase stamina, coordination and flexibility. SITC program is designed to provide working adults an opportunity to kick-start their workday with an invigorating workout, Sunrise in the City is a studio-gym based workout programme that was traditionally held in the mornings, but now includes lunchtime, weekend and afternoon sessions.In view of the current situation, virtual sessions are being piloted to provide participants with more opportunities to join in for the workout sessions online.</p ></div></div>';
document.getElementsByClassName("cards")[0].innerHTML += content;
